running: true
debugging: false

plot_size: 42000000
# plot_size: 73000000000
plot_directories:
    - /home/boon/plotting_folder01/
    - /home/boon/plotting_folder02/
destination_directories:
    - /mnt/sm487_01
    - /mnt/sm487_02
    - /mnt/sm487_03
destination_suffix: ghC8
obsolete_folder:
    - ghC7
    - Legacy
    - .
max_concurrent: 3
rsync_bw_limit: 30
